// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql"
	"time"
)

type GlobalSearch struct {
	EntityID   string `json:"entity_id"`
	EntityType string `json:"entity_type"`
	Entity     string `json:"entity"`
	Slug       string `json:"slug"`
	Address    string `json:"address"`
	SearchText string `json:"search_text"`
}

type Hostel struct {
	ID                  string          `json:"id"`
	Name                string          `json:"name"`
	Address             sql.NullString  `json:"address"`
	Description         sql.NullString  `json:"description"`
	City                sql.NullString  `json:"city"`
	Neighborhood        sql.NullString  `json:"neighborhood"`
	NeighborhoodID      sql.NullString  `json:"neighborhood_id"`
	Latitude            float64         `json:"latitude"`
	Longitude           float64         `json:"longitude"`
	GooglePlaceID       sql.NullString  `json:"google_place_id"`
	EstimatedPriceRange sql.NullFloat64 `json:"estimated_price_range"`
	DistanceToGateKm    sql.NullFloat64 `json:"distance_to_gate_km"`
	IsVerifiedByAdmin   sql.NullBool    `json:"is_verified_by_admin"`
	PrimaryPhotoUrl     sql.NullString  `json:"primary_photo_url"`
	Slug                string          `json:"slug"`
	CreatedAt           time.Time       `json:"created_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
}

type Institution struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Acronym   sql.NullString `json:"acronym"`
	Latitude  float64        `json:"latitude"`
	Longitude float64        `json:"longitude"`
	Slug      string         `json:"slug"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	City      string         `json:"city"`
}

type Neighborhood struct {
	ID                 string         `json:"id"`
	Institution        string         `json:"institution"`
	InstitutionID      string         `json:"institution_id"`
	Name               string         `json:"name"`
	AvgPriceSelfCon    sql.NullInt64  `json:"avg_price_self_con"`
	AvgPrice1bed       sql.NullInt64  `json:"avg_price_1bed"`
	PowerRatingInsight sql.NullString `json:"power_rating_insight"`
}

type PlaceSearch struct {
	PlaceID   string `json:"place_id"`
	PlaceType string `json:"place_type"`
	Name      string `json:"name"`
}

type User struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	FullName  string    `json:"full_name"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UserCredential struct {
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
	Provider     string         `json:"provider"`
	ProviderID   string         `json:"provider_id"`
	PasswordHash sql.NullString `json:"password_hash"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}
