// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql"
	"time"
)

type GlobalSearch struct {
	EntityID   string `json:"entity_id"`
	EntityType string `json:"entity_type"`
	Entity     string `json:"entity"`
	SearchText string `json:"search_text"`
}

type Hostel struct {
	ID                  string          `json:"id"`
	Name                string          `json:"name"`
	Address             sql.NullString  `json:"address"`
	City                sql.NullString  `json:"city"`
	Latitude            float64         `json:"latitude"`
	Longitude           float64         `json:"longitude"`
	GooglePlaceID       sql.NullString  `json:"google_place_id"`
	EstimatedPriceRange sql.NullString  `json:"estimated_price_range"`
	DistanceToGateKm    sql.NullFloat64 `json:"distance_to_gate_km"`
	EtaWalkingMins      sql.NullInt64   `json:"eta_walking_mins"`
	IsVerifiedByAdmin   sql.NullBool    `json:"is_verified_by_admin"`
	CreatedAt           time.Time       `json:"created_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
}

type Institution struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Acronym   sql.NullString `json:"acronym"`
	Latitude  float64        `json:"latitude"`
	Longitude float64        `json:"longitude"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	City      string         `json:"city"`
}

type User struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	FullName  string    `json:"full_name"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UserCredential struct {
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
	Provider     string         `json:"provider"`
	ProviderID   string         `json:"provider_id"`
	PasswordHash sql.NullString `json:"password_hash"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}
