// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"context"
	"database/sql"
)

type Querier interface {
	CheckHostelExists(ctx context.Context, name string) (int64, error)
	CheckInstitutionExists(ctx context.Context, slug string) (int64, error)
	CheckNeighborhoodExists(ctx context.Context, name string) (int64, error)
	CheckUserExists(ctx context.Context, email string) (int64, error)
	CreateHostel(ctx context.Context, arg CreateHostelParams) (Hostel, error)
	CreateInstitution(ctx context.Context, arg CreateInstitutionParams) (Institution, error)
	CreateNeighborhood(ctx context.Context, arg CreateNeighborhoodParams) (Neighborhood, error)
	CreatePlaceSearchEntry(ctx context.Context, arg CreatePlaceSearchEntryParams) (PlaceSearch, error)
	CreateSearchEntry(ctx context.Context, arg CreateSearchEntryParams) (GlobalSearch, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserCredentials(ctx context.Context, arg CreateUserCredentialsParams) (UserCredential, error)
	GetAllInstitutions(ctx context.Context) ([]Institution, error)
	GetAllNeighborhoods(ctx context.Context) ([]Neighborhood, error)
	GetHostel(ctx context.Context, id string) (Hostel, error)
	GetHostelBySlug(ctx context.Context, slug string) (Hostel, error)
	GetHostelsByCity(ctx context.Context, city sql.NullString) ([]Hostel, error)
	GetHostelsByInstitution(ctx context.Context, institutionID string) ([]Hostel, error)
	GetHostelsByNeighborhood(ctx context.Context, neighborhoodID sql.NullString) ([]Hostel, error)
	GetInstitutionById(ctx context.Context, id string) (Institution, error)
	GetInstitutionBySlug(ctx context.Context, slug string) (Institution, error)
	GetNeighborhoodById(ctx context.Context, id string) (Neighborhood, error)
	GetNeighborhoodsByInstitution(ctx context.Context, institutionID string) ([]Neighborhood, error)
	GetPlaceSearchEntry(ctx context.Context, name string) ([]PlaceSearch, error)
	GetSearchEntry(ctx context.Context, searchText string) ([]GetSearchEntryRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserCredentialByProviderId(ctx context.Context, providerID string) (UserCredential, error)
	ListInstitutions(ctx context.Context) ([]Institution, error)
}

var _ Querier = (*Queries)(nil)
