// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package models

import (
	"context"
	"database/sql"
)

const createHostel = `-- name: CreateHostel :one
INSERT INTO hostels (
    id, name, address, description, city, latitude, longitude,
    google_place_id, estimated_price_range,
    distance_to_gate_km, is_verified_by_admin, primary_photo_url, slug
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, name, address, description, city, latitude, longitude, google_place_id, estimated_price_range, distance_to_gate_km, is_verified_by_admin, primary_photo_url, slug, created_at, updated_at
`

type CreateHostelParams struct {
	ID                  string          `json:"id"`
	Name                string          `json:"name"`
	Address             sql.NullString  `json:"address"`
	Description         sql.NullString  `json:"description"`
	City                sql.NullString  `json:"city"`
	Latitude            float64         `json:"latitude"`
	Longitude           float64         `json:"longitude"`
	GooglePlaceID       sql.NullString  `json:"google_place_id"`
	EstimatedPriceRange sql.NullString  `json:"estimated_price_range"`
	DistanceToGateKm    sql.NullFloat64 `json:"distance_to_gate_km"`
	IsVerifiedByAdmin   sql.NullBool    `json:"is_verified_by_admin"`
	PrimaryPhotoUrl     sql.NullString  `json:"primary_photo_url"`
	Slug                string          `json:"slug"`
}

func (q *Queries) CreateHostel(ctx context.Context, arg CreateHostelParams) (Hostel, error) {
	row := q.db.QueryRowContext(ctx, createHostel,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Description,
		arg.City,
		arg.Latitude,
		arg.Longitude,
		arg.GooglePlaceID,
		arg.EstimatedPriceRange,
		arg.DistanceToGateKm,
		arg.IsVerifiedByAdmin,
		arg.PrimaryPhotoUrl,
		arg.Slug,
	)
	var i Hostel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Description,
		&i.City,
		&i.Latitude,
		&i.Longitude,
		&i.GooglePlaceID,
		&i.EstimatedPriceRange,
		&i.DistanceToGateKm,
		&i.IsVerifiedByAdmin,
		&i.PrimaryPhotoUrl,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInstitution = `-- name: CreateInstitution :one
INSERT INTO institutions (
    id, name, acronym, latitude, longitude, city, slug
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, name, acronym, latitude, longitude, slug, created_at, updated_at, city
`

type CreateInstitutionParams struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Acronym   sql.NullString `json:"acronym"`
	Latitude  float64        `json:"latitude"`
	Longitude float64        `json:"longitude"`
	City      string         `json:"city"`
	Slug      string         `json:"slug"`
}

func (q *Queries) CreateInstitution(ctx context.Context, arg CreateInstitutionParams) (Institution, error) {
	row := q.db.QueryRowContext(ctx, createInstitution,
		arg.ID,
		arg.Name,
		arg.Acronym,
		arg.Latitude,
		arg.Longitude,
		arg.City,
		arg.Slug,
	)
	var i Institution
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Acronym,
		&i.Latitude,
		&i.Longitude,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.City,
	)
	return i, err
}

const createSearchEntry = `-- name: CreateSearchEntry :one
INSERT INTO global_search (entity_id, entity_type, entity, search_text, slug)
VALUES (?, ?, ?, ?, ?)
RETURNING entity_id, entity_type, entity, slug, search_text
`

type CreateSearchEntryParams struct {
	EntityID   string `json:"entity_id"`
	EntityType string `json:"entity_type"`
	Entity     string `json:"entity"`
	SearchText string `json:"search_text"`
	Slug       string `json:"slug"`
}

func (q *Queries) CreateSearchEntry(ctx context.Context, arg CreateSearchEntryParams) (GlobalSearch, error) {
	row := q.db.QueryRowContext(ctx, createSearchEntry,
		arg.EntityID,
		arg.EntityType,
		arg.Entity,
		arg.SearchText,
		arg.Slug,
	)
	var i GlobalSearch
	err := row.Scan(
		&i.EntityID,
		&i.EntityType,
		&i.Entity,
		&i.Slug,
		&i.SearchText,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, full_name, email, role
) VALUES (
    ?, ?, ?, ?
)
RETURNING id, email, full_name, role, created_at, updated_at
`

type CreateUserParams struct {
	ID       string `json:"id"`
	FullName string `json:"full_name"`
	Email    string `json:"email"`
	Role     string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserCredentials = `-- name: CreateUserCredentials :one
INSERT INTO user_credentials (
    id, user_id, provider, provider_id, password_hash
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING id, user_id, provider, provider_id, password_hash, created_at, updated_at
`

type CreateUserCredentialsParams struct {
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
	Provider     string         `json:"provider"`
	ProviderID   string         `json:"provider_id"`
	PasswordHash sql.NullString `json:"password_hash"`
}

func (q *Queries) CreateUserCredentials(ctx context.Context, arg CreateUserCredentialsParams) (UserCredential, error) {
	row := q.db.QueryRowContext(ctx, createUserCredentials,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderID,
		arg.PasswordHash,
	)
	var i UserCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHostel = `-- name: GetHostel :one
SELECT id, name, address, description, city, latitude, longitude, google_place_id, estimated_price_range, distance_to_gate_km, is_verified_by_admin, primary_photo_url, slug, created_at, updated_at FROM hostels WHERE id = ? LIMIT 1
`

func (q *Queries) GetHostel(ctx context.Context, id string) (Hostel, error) {
	row := q.db.QueryRowContext(ctx, getHostel, id)
	var i Hostel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Description,
		&i.City,
		&i.Latitude,
		&i.Longitude,
		&i.GooglePlaceID,
		&i.EstimatedPriceRange,
		&i.DistanceToGateKm,
		&i.IsVerifiedByAdmin,
		&i.PrimaryPhotoUrl,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstitutionById = `-- name: GetInstitutionById :one
SELECT id, name, acronym, latitude, longitude, slug, created_at, updated_at, city FROM institutions WHERE id = ? LIMIT 1
`

func (q *Queries) GetInstitutionById(ctx context.Context, id string) (Institution, error) {
	row := q.db.QueryRowContext(ctx, getInstitutionById, id)
	var i Institution
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Acronym,
		&i.Latitude,
		&i.Longitude,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.City,
	)
	return i, err
}

const getSearchEntry = `-- name: GetSearchEntry :many
SELECT entity_id, entity_type, entity FROM global_search WHERE search_text MATCH ? ORDER BY rank LIMIT 5
`

type GetSearchEntryRow struct {
	EntityID   string `json:"entity_id"`
	EntityType string `json:"entity_type"`
	Entity     string `json:"entity"`
}

func (q *Queries) GetSearchEntry(ctx context.Context, searchText string) ([]GetSearchEntryRow, error) {
	rows, err := q.db.QueryContext(ctx, getSearchEntry, searchText)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSearchEntryRow{}
	for rows.Next() {
		var i GetSearchEntryRow
		if err := rows.Scan(&i.EntityID, &i.EntityType, &i.Entity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, full_name, role, created_at, updated_at FROM users WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCredentialByProviderId = `-- name: GetUserCredentialByProviderId :one
SELECT id, user_id, provider, provider_id, password_hash, created_at, updated_at FROM user_credentials WHERE provider_id = ? LIMIT 1
`

func (q *Queries) GetUserCredentialByProviderId(ctx context.Context, providerID string) (UserCredential, error) {
	row := q.db.QueryRowContext(ctx, getUserCredentialByProviderId, providerID)
	var i UserCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInstitutions = `-- name: ListInstitutions :many
SELECT id, name, acronym, latitude, longitude, slug, created_at, updated_at, city FROM institutions ORDER BY name
`

func (q *Queries) ListInstitutions(ctx context.Context) ([]Institution, error) {
	rows, err := q.db.QueryContext(ctx, listInstitutions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Institution{}
	for rows.Next() {
		var i Institution
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Acronym,
			&i.Latitude,
			&i.Longitude,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.City,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = ? LIMIT 1)
`

func (q *Queries) UserExists(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, userExists, email)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
