// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateHostel(ctx context.Context, arg CreateHostelParams) (Hostel, error)
	CreateInstitution(ctx context.Context, arg CreateInstitutionParams) (University, error)
	CreateNeighborhood(ctx context.Context, arg CreateNeighborhoodParams) (Neighborhood, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) (UserIdentity, error)
	GetHostel(ctx context.Context, id string) (Hostel, error)
	GetInstitution(ctx context.Context, id string) (University, error)
	GetNeighborhood(ctx context.Context, id string) (Neighborhood, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListHostelsByNeighborhood(ctx context.Context, neighborhoodID sql.NullString) ([]Hostel, error)
	ListNeighborhoodsByInstitution(ctx context.Context, universityID string) ([]Neighborhood, error)
	Listuniversities(ctx context.Context) ([]University, error)
}

var _ Querier = (*Queries)(nil)
