// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package models

import (
	"context"
	"database/sql"
)

const checkHostelExists = `-- name: CheckHostelExists :one
SELECT EXISTS(SELECT 1 FROM hostels WHERE LOWER(name) = ? LIMIT 1)
`

func (q *Queries) CheckHostelExists(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkHostelExists, name)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const checkInstitutionExists = `-- name: CheckInstitutionExists :one
SELECT EXISTS(SELECT 1 FROM institutions WHERE slug = ? LIMIT 1)
`

func (q *Queries) CheckInstitutionExists(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkInstitutionExists, slug)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const checkNeighborhoodExists = `-- name: CheckNeighborhoodExists :one
SELECT EXISTS(SELECT 1 FROM neighborhoods WHERE LOWER(name) = ? AND LOWER(city) = ? AND LOWER(institution) = ? LIMIT 1)
`

type CheckNeighborhoodExistsParams struct {
	Name        string `json:"name"`
	City        string `json:"city"`
	Institution string `json:"institution"`
}

func (q *Queries) CheckNeighborhoodExists(ctx context.Context, arg CheckNeighborhoodExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkNeighborhoodExists, arg.Name, arg.City, arg.Institution)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const checkUserExists = `-- name: CheckUserExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = ? LIMIT 1)
`

func (q *Queries) CheckUserExists(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkUserExists, email)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createHostel = `-- name: CreateHostel :one
INSERT INTO hostels (
    id, name, address, description, city, latitude, longitude,
    google_place_id, estimated_price_range, neighborhood, neighborhood_id,
    distance_to_gate_km, is_verified_by_admin, primary_photo_url, slug
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, name, address, description, city, neighborhood, neighborhood_id, latitude, longitude, google_place_id, estimated_price_range, distance_to_gate_km, is_verified_by_admin, primary_photo_url, slug, created_at, updated_at
`

type CreateHostelParams struct {
	ID                  string          `json:"id"`
	Name                string          `json:"name"`
	Address             sql.NullString  `json:"address"`
	Description         sql.NullString  `json:"description"`
	City                sql.NullString  `json:"city"`
	Latitude            float64         `json:"latitude"`
	Longitude           float64         `json:"longitude"`
	GooglePlaceID       sql.NullString  `json:"google_place_id"`
	EstimatedPriceRange sql.NullFloat64 `json:"estimated_price_range"`
	Neighborhood        sql.NullString  `json:"neighborhood"`
	NeighborhoodID      sql.NullString  `json:"neighborhood_id"`
	DistanceToGateKm    sql.NullFloat64 `json:"distance_to_gate_km"`
	IsVerifiedByAdmin   sql.NullBool    `json:"is_verified_by_admin"`
	PrimaryPhotoUrl     sql.NullString  `json:"primary_photo_url"`
	Slug                string          `json:"slug"`
}

func (q *Queries) CreateHostel(ctx context.Context, arg CreateHostelParams) (Hostel, error) {
	row := q.db.QueryRowContext(ctx, createHostel,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Description,
		arg.City,
		arg.Latitude,
		arg.Longitude,
		arg.GooglePlaceID,
		arg.EstimatedPriceRange,
		arg.Neighborhood,
		arg.NeighborhoodID,
		arg.DistanceToGateKm,
		arg.IsVerifiedByAdmin,
		arg.PrimaryPhotoUrl,
		arg.Slug,
	)
	var i Hostel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Description,
		&i.City,
		&i.Neighborhood,
		&i.NeighborhoodID,
		&i.Latitude,
		&i.Longitude,
		&i.GooglePlaceID,
		&i.EstimatedPriceRange,
		&i.DistanceToGateKm,
		&i.IsVerifiedByAdmin,
		&i.PrimaryPhotoUrl,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInstitution = `-- name: CreateInstitution :one
INSERT INTO institutions (
    id, name, acronym, latitude, longitude, city, slug
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, name, acronym, latitude, longitude, slug, created_at, updated_at, city
`

type CreateInstitutionParams struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Acronym   sql.NullString `json:"acronym"`
	Latitude  float64        `json:"latitude"`
	Longitude float64        `json:"longitude"`
	City      string         `json:"city"`
	Slug      string         `json:"slug"`
}

func (q *Queries) CreateInstitution(ctx context.Context, arg CreateInstitutionParams) (Institution, error) {
	row := q.db.QueryRowContext(ctx, createInstitution,
		arg.ID,
		arg.Name,
		arg.Acronym,
		arg.Latitude,
		arg.Longitude,
		arg.City,
		arg.Slug,
	)
	var i Institution
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Acronym,
		&i.Latitude,
		&i.Longitude,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.City,
	)
	return i, err
}

const createNeighborhood = `-- name: CreateNeighborhood :one
INSERT INTO neighborhoods (
    id, institution, institution_id, name, city, avg_price_self_con, avg_price_1bed, power_rating_insight
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, name, institution, institution_id, city, avg_price_self_con, avg_price_1bed, power_rating_insight
`

type CreateNeighborhoodParams struct {
	ID                 string         `json:"id"`
	Institution        string         `json:"institution"`
	InstitutionID      string         `json:"institution_id"`
	Name               string         `json:"name"`
	City               string         `json:"city"`
	AvgPriceSelfCon    sql.NullInt64  `json:"avg_price_self_con"`
	AvgPrice1bed       sql.NullInt64  `json:"avg_price_1bed"`
	PowerRatingInsight sql.NullString `json:"power_rating_insight"`
}

func (q *Queries) CreateNeighborhood(ctx context.Context, arg CreateNeighborhoodParams) (Neighborhood, error) {
	row := q.db.QueryRowContext(ctx, createNeighborhood,
		arg.ID,
		arg.Institution,
		arg.InstitutionID,
		arg.Name,
		arg.City,
		arg.AvgPriceSelfCon,
		arg.AvgPrice1bed,
		arg.PowerRatingInsight,
	)
	var i Neighborhood
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Institution,
		&i.InstitutionID,
		&i.City,
		&i.AvgPriceSelfCon,
		&i.AvgPrice1bed,
		&i.PowerRatingInsight,
	)
	return i, err
}

const createPlaceSearchEntry = `-- name: CreatePlaceSearchEntry :one
INSERT INTO place_search (place_id, place_type, name)
VALUES (?, ?, ?)
RETURNING place_id, place_type, name
`

type CreatePlaceSearchEntryParams struct {
	PlaceID   string `json:"place_id"`
	PlaceType string `json:"place_type"`
	Name      string `json:"name"`
}

func (q *Queries) CreatePlaceSearchEntry(ctx context.Context, arg CreatePlaceSearchEntryParams) (PlaceSearch, error) {
	row := q.db.QueryRowContext(ctx, createPlaceSearchEntry, arg.PlaceID, arg.PlaceType, arg.Name)
	var i PlaceSearch
	err := row.Scan(&i.PlaceID, &i.PlaceType, &i.Name)
	return i, err
}

const createSearchEntry = `-- name: CreateSearchEntry :one
INSERT INTO global_search (entity_id, entity_type, entity, search_text, slug, address)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING entity_id, entity_type, entity, slug, address, search_text
`

type CreateSearchEntryParams struct {
	EntityID   string `json:"entity_id"`
	EntityType string `json:"entity_type"`
	Entity     string `json:"entity"`
	SearchText string `json:"search_text"`
	Slug       string `json:"slug"`
	Address    string `json:"address"`
}

func (q *Queries) CreateSearchEntry(ctx context.Context, arg CreateSearchEntryParams) (GlobalSearch, error) {
	row := q.db.QueryRowContext(ctx, createSearchEntry,
		arg.EntityID,
		arg.EntityType,
		arg.Entity,
		arg.SearchText,
		arg.Slug,
		arg.Address,
	)
	var i GlobalSearch
	err := row.Scan(
		&i.EntityID,
		&i.EntityType,
		&i.Entity,
		&i.Slug,
		&i.Address,
		&i.SearchText,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, full_name, email, role
) VALUES (
    ?, ?, ?, ?
)
RETURNING id, email, full_name, role, created_at, updated_at
`

type CreateUserParams struct {
	ID       string `json:"id"`
	FullName string `json:"full_name"`
	Email    string `json:"email"`
	Role     string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserCredentials = `-- name: CreateUserCredentials :one
INSERT INTO user_credentials (
    id, user_id, provider, provider_id, password_hash
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING id, user_id, provider, provider_id, password_hash, created_at, updated_at
`

type CreateUserCredentialsParams struct {
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
	Provider     string         `json:"provider"`
	ProviderID   string         `json:"provider_id"`
	PasswordHash sql.NullString `json:"password_hash"`
}

func (q *Queries) CreateUserCredentials(ctx context.Context, arg CreateUserCredentialsParams) (UserCredential, error) {
	row := q.db.QueryRowContext(ctx, createUserCredentials,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderID,
		arg.PasswordHash,
	)
	var i UserCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllInstitutions = `-- name: GetAllInstitutions :many
SELECT id, name, acronym, latitude, longitude, slug, created_at, updated_at, city FROM institutions
`

func (q *Queries) GetAllInstitutions(ctx context.Context) ([]Institution, error) {
	rows, err := q.db.QueryContext(ctx, getAllInstitutions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Institution{}
	for rows.Next() {
		var i Institution
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Acronym,
			&i.Latitude,
			&i.Longitude,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.City,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllNeighborhoods = `-- name: GetAllNeighborhoods :many
SELECT id, name, institution, institution_id, city, avg_price_self_con, avg_price_1bed, power_rating_insight FROM neighborhoods ORDER BY name
`

func (q *Queries) GetAllNeighborhoods(ctx context.Context) ([]Neighborhood, error) {
	rows, err := q.db.QueryContext(ctx, getAllNeighborhoods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Neighborhood{}
	for rows.Next() {
		var i Neighborhood
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Institution,
			&i.InstitutionID,
			&i.City,
			&i.AvgPriceSelfCon,
			&i.AvgPrice1bed,
			&i.PowerRatingInsight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHostel = `-- name: GetHostel :one
SELECT id, name, address, description, city, neighborhood, neighborhood_id, latitude, longitude, google_place_id, estimated_price_range, distance_to_gate_km, is_verified_by_admin, primary_photo_url, slug, created_at, updated_at FROM hostels WHERE id = ? LIMIT 1
`

func (q *Queries) GetHostel(ctx context.Context, id string) (Hostel, error) {
	row := q.db.QueryRowContext(ctx, getHostel, id)
	var i Hostel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Description,
		&i.City,
		&i.Neighborhood,
		&i.NeighborhoodID,
		&i.Latitude,
		&i.Longitude,
		&i.GooglePlaceID,
		&i.EstimatedPriceRange,
		&i.DistanceToGateKm,
		&i.IsVerifiedByAdmin,
		&i.PrimaryPhotoUrl,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHostelBySlug = `-- name: GetHostelBySlug :one
SELECT id, name, address, description, city, neighborhood, neighborhood_id, latitude, longitude, google_place_id, estimated_price_range, distance_to_gate_km, is_verified_by_admin, primary_photo_url, slug, created_at, updated_at FROM hostels WHERE slug = ? LIMIT 1
`

func (q *Queries) GetHostelBySlug(ctx context.Context, slug string) (Hostel, error) {
	row := q.db.QueryRowContext(ctx, getHostelBySlug, slug)
	var i Hostel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Description,
		&i.City,
		&i.Neighborhood,
		&i.NeighborhoodID,
		&i.Latitude,
		&i.Longitude,
		&i.GooglePlaceID,
		&i.EstimatedPriceRange,
		&i.DistanceToGateKm,
		&i.IsVerifiedByAdmin,
		&i.PrimaryPhotoUrl,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHostelsByCity = `-- name: GetHostelsByCity :many
SELECT id, name, address, description, city, neighborhood, neighborhood_id, latitude, longitude, google_place_id, estimated_price_range, distance_to_gate_km, is_verified_by_admin, primary_photo_url, slug, created_at, updated_at FROM hostels WHERE city = ? ORDER BY name
`

func (q *Queries) GetHostelsByCity(ctx context.Context, city sql.NullString) ([]Hostel, error) {
	rows, err := q.db.QueryContext(ctx, getHostelsByCity, city)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Hostel{}
	for rows.Next() {
		var i Hostel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Description,
			&i.City,
			&i.Neighborhood,
			&i.NeighborhoodID,
			&i.Latitude,
			&i.Longitude,
			&i.GooglePlaceID,
			&i.EstimatedPriceRange,
			&i.DistanceToGateKm,
			&i.IsVerifiedByAdmin,
			&i.PrimaryPhotoUrl,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHostelsByInstitution = `-- name: GetHostelsByInstitution :many
SELECT hostels.id, hostels.name, hostels.address, hostels.description, hostels.city, hostels.neighborhood, hostels.neighborhood_id, hostels.latitude, hostels.longitude, hostels.google_place_id, hostels.estimated_price_range, hostels.distance_to_gate_km, hostels.is_verified_by_admin, hostels.primary_photo_url, hostels.slug, hostels.created_at, hostels.updated_at FROM hostels INNER JOIN neighborhoods ON hostels.neighborhood_id = neighborhoods.id WHERE neighborhoods.institution_id = ?
`

func (q *Queries) GetHostelsByInstitution(ctx context.Context, institutionID string) ([]Hostel, error) {
	rows, err := q.db.QueryContext(ctx, getHostelsByInstitution, institutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Hostel{}
	for rows.Next() {
		var i Hostel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Description,
			&i.City,
			&i.Neighborhood,
			&i.NeighborhoodID,
			&i.Latitude,
			&i.Longitude,
			&i.GooglePlaceID,
			&i.EstimatedPriceRange,
			&i.DistanceToGateKm,
			&i.IsVerifiedByAdmin,
			&i.PrimaryPhotoUrl,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHostelsByNeighborhood = `-- name: GetHostelsByNeighborhood :many
SELECT id, name, address, description, city, neighborhood, neighborhood_id, latitude, longitude, google_place_id, estimated_price_range, distance_to_gate_km, is_verified_by_admin, primary_photo_url, slug, created_at, updated_at FROM hostels WHERE neighborhood_id = ? ORDER BY name
`

func (q *Queries) GetHostelsByNeighborhood(ctx context.Context, neighborhoodID sql.NullString) ([]Hostel, error) {
	rows, err := q.db.QueryContext(ctx, getHostelsByNeighborhood, neighborhoodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Hostel{}
	for rows.Next() {
		var i Hostel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Description,
			&i.City,
			&i.Neighborhood,
			&i.NeighborhoodID,
			&i.Latitude,
			&i.Longitude,
			&i.GooglePlaceID,
			&i.EstimatedPriceRange,
			&i.DistanceToGateKm,
			&i.IsVerifiedByAdmin,
			&i.PrimaryPhotoUrl,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstitutionById = `-- name: GetInstitutionById :one
SELECT id, name, acronym, latitude, longitude, slug, created_at, updated_at, city FROM institutions WHERE id = ? LIMIT 1
`

func (q *Queries) GetInstitutionById(ctx context.Context, id string) (Institution, error) {
	row := q.db.QueryRowContext(ctx, getInstitutionById, id)
	var i Institution
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Acronym,
		&i.Latitude,
		&i.Longitude,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.City,
	)
	return i, err
}

const getInstitutionBySlug = `-- name: GetInstitutionBySlug :one
SELECT id, name, acronym, latitude, longitude, slug, created_at, updated_at, city FROM institutions WHERE slug = ? LIMIT 1
`

func (q *Queries) GetInstitutionBySlug(ctx context.Context, slug string) (Institution, error) {
	row := q.db.QueryRowContext(ctx, getInstitutionBySlug, slug)
	var i Institution
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Acronym,
		&i.Latitude,
		&i.Longitude,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.City,
	)
	return i, err
}

const getNeighborhoodById = `-- name: GetNeighborhoodById :one
SELECT id, name, institution, institution_id, city, avg_price_self_con, avg_price_1bed, power_rating_insight FROM neighborhoods WHERE id = ? LIMIT 1
`

func (q *Queries) GetNeighborhoodById(ctx context.Context, id string) (Neighborhood, error) {
	row := q.db.QueryRowContext(ctx, getNeighborhoodById, id)
	var i Neighborhood
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Institution,
		&i.InstitutionID,
		&i.City,
		&i.AvgPriceSelfCon,
		&i.AvgPrice1bed,
		&i.PowerRatingInsight,
	)
	return i, err
}

const getNeighborhoodsByInstitution = `-- name: GetNeighborhoodsByInstitution :many
SELECT id, name, institution, institution_id, city, avg_price_self_con, avg_price_1bed, power_rating_insight FROM neighborhoods WHERE institution_id = ? ORDER BY name
`

func (q *Queries) GetNeighborhoodsByInstitution(ctx context.Context, institutionID string) ([]Neighborhood, error) {
	rows, err := q.db.QueryContext(ctx, getNeighborhoodsByInstitution, institutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Neighborhood{}
	for rows.Next() {
		var i Neighborhood
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Institution,
			&i.InstitutionID,
			&i.City,
			&i.AvgPriceSelfCon,
			&i.AvgPrice1bed,
			&i.PowerRatingInsight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaceSearchEntry = `-- name: GetPlaceSearchEntry :many
SELECT place_id, place_type, name FROM place_search WHERE name MATCH ? ORDER BY rank LIMIT 5
`

func (q *Queries) GetPlaceSearchEntry(ctx context.Context, name string) ([]PlaceSearch, error) {
	rows, err := q.db.QueryContext(ctx, getPlaceSearchEntry, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlaceSearch{}
	for rows.Next() {
		var i PlaceSearch
		if err := rows.Scan(&i.PlaceID, &i.PlaceType, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSearchEntry = `-- name: GetSearchEntry :many
SELECT entity_id, entity_type, entity, slug, address FROM global_search WHERE search_text MATCH ? ORDER BY rank LIMIT 5
`

type GetSearchEntryRow struct {
	EntityID   string `json:"entity_id"`
	EntityType string `json:"entity_type"`
	Entity     string `json:"entity"`
	Slug       string `json:"slug"`
	Address    string `json:"address"`
}

func (q *Queries) GetSearchEntry(ctx context.Context, searchText string) ([]GetSearchEntryRow, error) {
	rows, err := q.db.QueryContext(ctx, getSearchEntry, searchText)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSearchEntryRow{}
	for rows.Next() {
		var i GetSearchEntryRow
		if err := rows.Scan(
			&i.EntityID,
			&i.EntityType,
			&i.Entity,
			&i.Slug,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, full_name, role, created_at, updated_at FROM users WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCredentialByProviderId = `-- name: GetUserCredentialByProviderId :one
SELECT id, user_id, provider, provider_id, password_hash, created_at, updated_at FROM user_credentials WHERE provider_id = ? LIMIT 1
`

func (q *Queries) GetUserCredentialByProviderId(ctx context.Context, providerID string) (UserCredential, error) {
	row := q.db.QueryRowContext(ctx, getUserCredentialByProviderId, providerID)
	var i UserCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInstitutions = `-- name: ListInstitutions :many
SELECT id, name, acronym, latitude, longitude, slug, created_at, updated_at, city FROM institutions ORDER BY name
`

func (q *Queries) ListInstitutions(ctx context.Context) ([]Institution, error) {
	rows, err := q.db.QueryContext(ctx, listInstitutions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Institution{}
	for rows.Next() {
		var i Institution
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Acronym,
			&i.Latitude,
			&i.Longitude,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.City,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
