// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package models

import (
	"context"
	"database/sql"
)

const createHostel = `-- name: CreateHostel :one
INSERT INTO hostels (
    id, neighborhood_id, name, address, latitude, longitude,
    google_place_id, google_rating, estimated_price_range,
    distance_to_gate_km, eta_walking_mins, is_verified_by_admin
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, neighborhood_id, name, address, latitude, longitude, google_place_id, google_rating, estimated_price_range, distance_to_gate_km, eta_walking_mins, is_verified_by_admin, created_at, updated_at
`

type CreateHostelParams struct {
	ID                  string          `json:"id"`
	NeighborhoodID      sql.NullString  `json:"neighborhood_id"`
	Name                string          `json:"name"`
	Address             sql.NullString  `json:"address"`
	Latitude            float64         `json:"latitude"`
	Longitude           float64         `json:"longitude"`
	GooglePlaceID       sql.NullString  `json:"google_place_id"`
	GoogleRating        sql.NullFloat64 `json:"google_rating"`
	EstimatedPriceRange sql.NullString  `json:"estimated_price_range"`
	DistanceToGateKm    sql.NullFloat64 `json:"distance_to_gate_km"`
	EtaWalkingMins      sql.NullInt64   `json:"eta_walking_mins"`
	IsVerifiedByAdmin   sql.NullBool    `json:"is_verified_by_admin"`
}

func (q *Queries) CreateHostel(ctx context.Context, arg CreateHostelParams) (Hostel, error) {
	row := q.db.QueryRowContext(ctx, createHostel,
		arg.ID,
		arg.NeighborhoodID,
		arg.Name,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.GooglePlaceID,
		arg.GoogleRating,
		arg.EstimatedPriceRange,
		arg.DistanceToGateKm,
		arg.EtaWalkingMins,
		arg.IsVerifiedByAdmin,
	)
	var i Hostel
	err := row.Scan(
		&i.ID,
		&i.NeighborhoodID,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.GooglePlaceID,
		&i.GoogleRating,
		&i.EstimatedPriceRange,
		&i.DistanceToGateKm,
		&i.EtaWalkingMins,
		&i.IsVerifiedByAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInstitution = `-- name: CreateInstitution :one
INSERT INTO universities (
    id, name, acronym, latitude, longitude
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING id, name, acronym, latitude, longitude
`

type CreateInstitutionParams struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Acronym   sql.NullString `json:"acronym"`
	Latitude  float64        `json:"latitude"`
	Longitude float64        `json:"longitude"`
}

func (q *Queries) CreateInstitution(ctx context.Context, arg CreateInstitutionParams) (University, error) {
	row := q.db.QueryRowContext(ctx, createInstitution,
		arg.ID,
		arg.Name,
		arg.Acronym,
		arg.Latitude,
		arg.Longitude,
	)
	var i University
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Acronym,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const createNeighborhood = `-- name: CreateNeighborhood :one
INSERT INTO neighborhoods (
    id, university_id, name, avg_price_self_con, avg_price_1bed,
    power_rating_insight, latitude, longitude
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, university_id, name, avg_price_self_con, avg_price_1bed, power_rating_insight, latitude, longitude
`

type CreateNeighborhoodParams struct {
	ID                 string         `json:"id"`
	UniversityID       string         `json:"university_id"`
	Name               string         `json:"name"`
	AvgPriceSelfCon    sql.NullInt64  `json:"avg_price_self_con"`
	AvgPrice1bed       sql.NullInt64  `json:"avg_price_1bed"`
	PowerRatingInsight sql.NullString `json:"power_rating_insight"`
	Latitude           float64        `json:"latitude"`
	Longitude          float64        `json:"longitude"`
}

func (q *Queries) CreateNeighborhood(ctx context.Context, arg CreateNeighborhoodParams) (Neighborhood, error) {
	row := q.db.QueryRowContext(ctx, createNeighborhood,
		arg.ID,
		arg.UniversityID,
		arg.Name,
		arg.AvgPriceSelfCon,
		arg.AvgPrice1bed,
		arg.PowerRatingInsight,
		arg.Latitude,
		arg.Longitude,
	)
	var i Neighborhood
	err := row.Scan(
		&i.ID,
		&i.UniversityID,
		&i.Name,
		&i.AvgPriceSelfCon,
		&i.AvgPrice1bed,
		&i.PowerRatingInsight,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, full_name, email, role
) VALUES (
    ?, ?, ?, ?
)
RETURNING id, email, full_name, role, created_at, updated_at
`

type CreateUserParams struct {
	ID       string `json:"id"`
	FullName string `json:"full_name"`
	Email    string `json:"email"`
	Role     string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserIdentity = `-- name: CreateUserIdentity :one
INSERT INTO user_identities (
    id, user_id, provider, provider_id
) VALUES (
    ?, ?, ?, ?
)
RETURNING id, user_id, provider, provider_id, created_at, updated_at
`

type CreateUserIdentityParams struct {
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
}

func (q *Queries) CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRowContext(ctx, createUserIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderID,
	)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHostel = `-- name: GetHostel :one
SELECT id, neighborhood_id, name, address, latitude, longitude, google_place_id, google_rating, estimated_price_range, distance_to_gate_km, eta_walking_mins, is_verified_by_admin, created_at, updated_at FROM hostels WHERE id = ? LIMIT 1
`

func (q *Queries) GetHostel(ctx context.Context, id string) (Hostel, error) {
	row := q.db.QueryRowContext(ctx, getHostel, id)
	var i Hostel
	err := row.Scan(
		&i.ID,
		&i.NeighborhoodID,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.GooglePlaceID,
		&i.GoogleRating,
		&i.EstimatedPriceRange,
		&i.DistanceToGateKm,
		&i.EtaWalkingMins,
		&i.IsVerifiedByAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstitution = `-- name: GetInstitution :one
SELECT id, name, acronym, latitude, longitude FROM universities WHERE id = ? LIMIT 1
`

func (q *Queries) GetInstitution(ctx context.Context, id string) (University, error) {
	row := q.db.QueryRowContext(ctx, getInstitution, id)
	var i University
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Acronym,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getNeighborhood = `-- name: GetNeighborhood :one
SELECT id, university_id, name, avg_price_self_con, avg_price_1bed, power_rating_insight, latitude, longitude FROM neighborhoods WHERE id = ? LIMIT 1
`

func (q *Queries) GetNeighborhood(ctx context.Context, id string) (Neighborhood, error) {
	row := q.db.QueryRowContext(ctx, getNeighborhood, id)
	var i Neighborhood
	err := row.Scan(
		&i.ID,
		&i.UniversityID,
		&i.Name,
		&i.AvgPriceSelfCon,
		&i.AvgPrice1bed,
		&i.PowerRatingInsight,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, full_name, role, created_at, updated_at FROM users WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHostelsByNeighborhood = `-- name: ListHostelsByNeighborhood :many
SELECT id, neighborhood_id, name, address, latitude, longitude, google_place_id, google_rating, estimated_price_range, distance_to_gate_km, eta_walking_mins, is_verified_by_admin, created_at, updated_at FROM hostels
WHERE neighborhood_id = ?
ORDER BY is_verified_by_admin DESC, name
`

func (q *Queries) ListHostelsByNeighborhood(ctx context.Context, neighborhoodID sql.NullString) ([]Hostel, error) {
	rows, err := q.db.QueryContext(ctx, listHostelsByNeighborhood, neighborhoodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Hostel{}
	for rows.Next() {
		var i Hostel
		if err := rows.Scan(
			&i.ID,
			&i.NeighborhoodID,
			&i.Name,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.GooglePlaceID,
			&i.GoogleRating,
			&i.EstimatedPriceRange,
			&i.DistanceToGateKm,
			&i.EtaWalkingMins,
			&i.IsVerifiedByAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNeighborhoodsByInstitution = `-- name: ListNeighborhoodsByInstitution :many
SELECT id, university_id, name, avg_price_self_con, avg_price_1bed, power_rating_insight, latitude, longitude FROM neighborhoods
WHERE university_id = ?
ORDER BY name
`

func (q *Queries) ListNeighborhoodsByInstitution(ctx context.Context, universityID string) ([]Neighborhood, error) {
	rows, err := q.db.QueryContext(ctx, listNeighborhoodsByInstitution, universityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Neighborhood{}
	for rows.Next() {
		var i Neighborhood
		if err := rows.Scan(
			&i.ID,
			&i.UniversityID,
			&i.Name,
			&i.AvgPriceSelfCon,
			&i.AvgPrice1bed,
			&i.PowerRatingInsight,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listuniversities = `-- name: Listuniversities :many
SELECT id, name, acronym, latitude, longitude FROM universities ORDER BY name
`

func (q *Queries) Listuniversities(ctx context.Context) ([]University, error) {
	rows, err := q.db.QueryContext(ctx, listuniversities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []University{}
	for rows.Next() {
		var i University
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Acronym,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = ? LIMIT 1)
`

func (q *Queries) UserExists(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, userExists, email)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
