# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  DB_URL: postgres://enoch:enoch1234@localhost:5432/dorms_ng?sslmode=disable

tasks:
  dev:
    desc: Run the development server
    cmds:
      - air
  test:
    desc: Run tests
    cmds:
      - go test ./... -v -count=1
  test-race:
    desc: Run unit tests with race checks
    cmds:
      - go test ./... -v -count=1 -race -tags=!integration
  test-race-cover:
    desc: Run unit tests with race checks and coverage
    cmds:
      - go test ./... -v -count=1 -race -cover -tags=!integration
  test-integration:
    desc: Run integration tests
    cmds:
      - go test ./... -v -count=1 -tags=integration
  build:
    desc: Build the application
    cmds:
      - go build -o main ./cmd/api/main.go
  sqlc:
    desc: Generate SQLC bindings
    cmds:
      - sqlc generate
  migrate:
    desc: Run database migrations
    cmds:
      - goose -dir internal/database/migrations postgres {{.DB_URL}} up
  rollback:
    desc: Rollback the database
    cmds:
      - goose -dir internal/database/migrations postgres {{.DB_URL}} down
  db-reset:
    desc: Reset the database
    cmds:
      - goose -dir internal/database/migrations postgres {{.DB_URL}} reset
  tidy:
    desc: clean up go mod
    cmds:
      - go mod tidy
