# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  DB_URL: internal/database/data.db

tasks:
  dev:
    desc: Run the development server
    cmds:
      - air
  build:
    desc: Build the application
    cmds:
      - go build -o main ./cmd/api/main.go
  generate-sql:
    desc: Generate SQLC bindings
    cmds:
      - sqlc generate
  migrate:
    desc: Run database migrations
    cmds:
      - goose -dir internal/database/migrations sqlite3 {{.DB_URL}} up
  rollback:
    desc: Rollback the database
    cmds:
      - goose -dir internal/database/migrations sqlite3 {{.DB_URL}} down
  db-reset:
    desc: Reset the database
    cmds:
      - goose -dir internal/database/migrations sqlite3 {{.DB_URL}} reset
  tidy:
    desc: clean up go mod
    cmds:
      - go mod tidy
